version: '2'
services:
  web:
    depends_on:
    - db
    - cache
    image: poll-app
    ports:
    - "8000:80"
    volumes:
      - /Users/alekseychu/git_repos/vk-poll:/var/www
  db:
    image: mysql:5.7
    volumes:
    - /Users/alekseychu/git_repos/vk-poll/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: 123
  cache:
    image: memcached
